### ISSUE TITLE
If no .ass file comes down from CR, it fails to convert the file to mkv. 

### ISSUE THREAD

**Issue by zenjabba** [BeardOverflow/MergeCrunch#1]
Comes up with an error, and trying to figure out the logic. Would be simply better to copy the .mp4 to the final destination.

**Comment by BeardOverflow** [comment]
For testing purpose, could you paste here a sample URL for a video which does not include a subtitle track?

**Comment by zenjabba** [comment]
STEP 0. QUEUE INPUT URL #1.
http://www.crunchyroll.com/blassreiter/episode-1-prelude-to-despair-318035
STEP 1. GET CRUNCHYROLL STREAMING DOWNLOAD.
[crunchyroll] 318035: Downloading webpage
[crunchyroll] 318035: Downloading jaJP m3u8 information
[crunchyroll] 318035: Downloading media info
[download] Destination: BLASSREITER Episode 1 – Prelude to Despair-318035.mp4
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, hls,applehttp, from 'https://v.vrv.co/evs/fe256da5caa810088ceaccc702a3e5d7/assets/izsmb3gm9wuh1nf_1507133.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvZmUyNTZkYTVjYWE4MTAwODhjZWFjY2M3MDJhM2U1ZDcvYXNzZXRzLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1MzczNjk0Mjd9fX1dfQ__&Signature=V6xcD7OwI2pgH8L4DKBspflYwjTMXHRfzUNFbFxFz72rCfeKJnNW67cL9ELkGUPKOsCObSX79RKiTkFaXyIqPL6SYdsFdPOua0bXjaapA~pHNzK9ZIOf7D1UIiIIZx0NCjgbLeLtUPNeTP~oAKna3IJ8t39ikWFgo1T9u2xHkLVbVUqzM3lEWsTmFrHT1uw0X-PYztujIS2s3ScoZnZKXbjMJ2Unwws2T2btZiKPTV0lPn1nb3Gi-PGuFU-Sv2TKX2o~fLdy~JvsjT3Gsg9EWRrJmB5qEiGtzhllzUkLgHXYX1uktFqDd2SChhOblUcabyUMJ3NdYUmePIbukn7LkA__&Key-Pair-Id=APKAJKQQ2INNHTYFB44A':
  Duration: 00:23:43.97, start: 0.101000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 848x480 [SAR 1014:1007 DAR 169:95], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 89 kb/s
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
[mp4 @ 0x2a8b3e0] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x2a8b3e0] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:BLASSREITER Episode 1 – Prelude to Despair-318035.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 848x480 [SAR 1014:1007 DAR 169:95], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 89 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=34141 fps=912 q=-1.0 Lsize=  264310kB time=00:23:43.96 bitrate=1520.6kbits/s
video:246390kB audio:16687kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.468689%
[ffmpeg] Downloaded 270653511 bytes
[download] 100% of 258.12MiB in 00:38
STEP 2. CHECKING AVAILABLE SUBTITLES.
Found  subtitle!... Ready.
STEP 3. CHECKING AVAILABLES ATTACHMENT FONTS TEXT.
cat: '*.ass': No such file or directory
WARNING: REQUEST FONT <<<  >>> IS NOT INSTALLED IN YOUR SYSTEM. PLEASE, INSTALL IT AND TRY AGAIN. WHILE I WILL BE USE <<< DejaVu Sans >>>.
STEP 4. TIME TO MERGING ALL TO MKV FILE.
Error: Invalid language specified in '--language 0:'.
^CSignal received! Abort all and exit!

**Comment by zenjabba** [comment]
*http://www.crunchyroll.com/blassreiter/*

**Comment by BeardOverflow** [comment]
Thanks for contributing to fix this bug. It is fixed now.

**Comment by zenjabba** [comment]
Always welcome… glad I could help and give you specific information you needed.
