### ISSUE TITLE
If files name has `, script fails to process merge

### ISSUE THREAD

**Issue by zenjabba** [BeardOverflow/MergeCrunch#2]
file:Glass Mask Episode 2 – Vivi`s Mask-522316.mp4

**Comment by zenjabba** [comment]
http://www.crunchyroll.com/glass-mask#2,13

**Comment by BeardOverflow** [comment]
Even I had trouble to write the commit message!

It's done, thanks for reporting :+1:

**Comment by zenjabba** [comment]
Confirm working
