### ISSUE TITLE
Issue with this file unable to process. I've checked the permissions, but it seems to be something funcky with the script.

### ISSUE THREAD

**Issue by zenjabba** [BeardOverflow/MergeCrunch#3]
`./mergecrunch.sh -i http://www.crunchyroll.com/hi-scool-seha-girls#11`

Output #0, mp4, to 'file:Hi-sCool! Seha Girls Episode 11 – Dream Rappy, Saturn Rappy, Mega Rappy,  Rappy-661667.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=20381 fps=633 q=-1.0 Lsize=  643496kB time=00:11:20.08 bitrate=7751.2kbits/s
video:632112kB audio:10626kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.117858%
[ffmpeg] Downloaded 658940296 bytes
[download] 100% of 628.41MiB in 00:32
STEP 2. CHECKING AVAILABLE SUBTITLES.
Found English (USA) subtitle!... Ready.
Found Español (México) subtitle!... Ready.
Found Português (Brasil) subtitle!... Ready.
STEP 3. CHECKING AVAILABLES ATTACHMENT FONTS TEXT.
Found Arial font!... Ready.
Found Comic Sans MS font!... Ready.
Found Times New Roman font!... Ready.
Found Trebuchet MS font!... Ready.
STEP 4. TIME FOR MERGING ALL TO MKV FILE.
Error: The file 'Hi-sCool! Seha Girls Episode 11 – Dream Rappy, Saturn Rappy, Mega Rappy, Rappy-661667.mp4' could not be opened for reading: open file error.

**Comment by BeardOverflow** [comment]
You are a great tester!
Thanks again for reporting this issue. The title contains double spaces and was trimmed accidentally.

**Comment by zenjabba** [comment]
Confirmed fixed.
