### ISSUE TITLE
Error: Invalid language specified in '--language 0:'.

### ISSUE THREAD

**Issue by zenjabba** [BeardOverflow/MergeCrunch#4]
http://www.crunchyroll.com/monster-strike/episode-2-slingshot-away-call-me-oragon-725503
STEP 1. GET CRUNCHYROLL STREAMING DOWNLOAD.
[crunchyroll] 725503: Downloading webpage
[crunchyroll] 725503: Downloading deDE m3u8 information
[crunchyroll] 725503: Downloading esES m3u8 information
[crunchyroll] 725503: Downloading jaJP m3u8 information
[crunchyroll] 725503: Downloading frFR m3u8 information
[crunchyroll] 725503: Downloading ptBR m3u8 information
[crunchyroll] 725503: Downloading esLA m3u8 information
[crunchyroll] 725503: Downloading ptPT m3u8 information
[crunchyroll] 725503: Downloading enUS m3u8 information
[crunchyroll] 725503: Downloading media info
[info] Writing video subtitles to: Monster Strike Anime 2016 Episode 2 – Slingshot Away! Call Me Oragon!-725503.frFR.ass
[info] Writing video subtitles to: Monster Strike Anime 2016 Episode 2 – Slingshot Away! Call Me Oragon!-725503.deDE.ass
[info] Writing video subtitles to: Monster Strike Anime 2016 Episode 2 – Slingshot Away! Call Me Oragon!-725503.esLA.ass
[info] Writing video subtitles to: Monster Strike Anime 2016 Episode 2 – Slingshot Away! Call Me Oragon!-725503.enUS.ass
[info] Writing video subtitles to: Monster Strike Anime 2016 Episode 2 – Slingshot Away! Call Me Oragon!-725503.esES.ass
[info] Writing video subtitles to: Monster Strike Anime 2016 Episode 2 – Slingshot Away! Call Me Oragon!-725503.ptBR.ass
[info] Writing video subtitles to: Monster Strike Anime 2016 Episode 2 – Slingshot Away! Call Me Oragon!-725503.ptPT.ass
[download] Destination: Monster Strike Anime 2016 Episode 2 – Slingshot Away! Call Me Oragon!-725503.mp4
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, hls,applehttp, from 'https://v.vrv.co/evs/cdb4e9b268c98bea9479fda561d61d7e/assets/8e0ee396fb8c58071e791d24e4057a79_3015521.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvY2RiNGU5YjI2OGM5OGJlYTk0NzlmZGE1NjFkNjFkN2UvYXNzZXRzLzhlMGVlMzk2ZmI4YzU4MDcxZTc5MWQyNGU0MDU3YTc5XyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1Mzg0MjgwOTF9fX1dfQ__&Signature=ABGgZ49~nvpsadGAwulH7S4~jY0nT2XerIMdXIz4WrdTKkzx7xj3-ERfxVoX4oeNskiHiRycee7SnhhtgNczpmzTp8EiAUCGvolAwFtSMSm1zMFbRpCMQP6XI4I1~U-UBuqd0a~CM6x0HJf-4tZfqcpVRRofeamFguxia9InJ0zrKBJwnXuequjtp3-jlE~g1WlY2GSHI7LkSiTLFn6dPJoaQ8RBny9AK4zBXlBuq3Chfonujn55hwo8PGq2tmHBJwxWoh-nsJI~elPu0A4vo4w4w5LQaDFuZlc8CHMwnPKVR97gMMK~bitKpBfoefnFqTnw-Y13F0oLad5Omgbutw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA':
  Duration: 00:08:37.52, start: 0.101000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 138 kb/s
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
[mp4 @ 0x20e2a80] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x20e2a80] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:Monster Strike Anime 2016 Episode 2 – Slingshot Away! Call Me Oragon!-725503.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 138 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=12408 fps=584 q=-1.0 Lsize=  351722kB time=00:08:37.57 bitrate=5567.0kbits/s
video:343171kB audio:8087kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.131949%
[ffmpeg] Downloaded 360162975 bytes
[download] 100% of 343.48MiB in 00:22
STEP 2. CHECKING AVAILABLE SUBTITLES.
Found Deutsch (Deutschland) subtitle!... Ready.
Found English (USA) subtitle!... Ready.
Found Español (España) subtitle!... Ready.
Found Español (México) subtitle!... Ready.
Found Français (France) subtitle!... Ready.
Found Português (Brasil) subtitle!... Ready.
Found  subtitle!... Ready.
STEP 3. CHECKING AVAILABLES ATTACHMENT FONTS TEXT.
Found Arial font!... Ready.
Found Trebuchet MS font!... Ready.
STEP 4. TIME FOR MERGING ALL TO MKV FILE.
Error: Invalid language specified in '--language 0:'.
Merge failed! Exitting...

**Comment by zenjabba** [comment]
./mergecrunch.sh -i http://www.crunchyroll.com/monster-strike#2,3,4,5,8,9 -f best -s enUS -c /home/xxxx/cookies.txt -o "/home/xxxx/gdrive/complete/incomplete/monster-strike/"

**Comment by BeardOverflow** [comment]
Just now I cannot review this error because of another bug affects to youtube-dl
https://github.com/rg3/youtube-dl/issues/17749

**Comment by zenjabba** [comment]
Understood. I'll watch the other bug as well.

**Comment by BeardOverflow** [comment]
You had discovered two bugs:
- The code doesn't handle missing patterns properly and the ptPT pattern was missing.
- When substitution history feature is enabled, a string such as !. calls to previous executed commands.

**Comment by zenjabba** [comment]
I find too many bugs.. sorry :)

**Comment by zenjabba** [comment]
confirmed fixed after updating with `youtube-dl -U`
