### ISSUE TITLE
Can we make this also support Funimation

### ISSUE THREAD

**Issue by zenjabba** [BeardOverflow/MergeCrunch#6]
Would it be possible to make this magic support funimation. It seems perfect for what it does and would make a great update.

**Comment by BeardOverflow** [comment]
Mainly youtube-dl must offer to support to Funimation. I haven't done any test, but if Funimation is supported by youtube-dl, I would support it too.
The codebase is a bit awful, so I will need to refactor it previously.

**Comment by zenjabba** [comment]
Funimation
https://rg3.github.io/youtube-dl/supportedsites.html

**Comment by BeardOverflow** [comment]
Youtube-dl haven't supported Funimation for a long time. The most common errors are "ERROR: Unable to extract al:web:url" and "JSON object could be decoded".

I am sorry, but I am going to close this issue.
