### ISSUE TITLE
Enter user agent in script code!

### ISSUE THREAD

**Issue by arbarbosa1979** [BeardOverflow/MergeCrunch#7]
How can I enter the command **--user-agent** in your script? There was a change in crunchyroll, and you can only resolve by entering that command.

**Comment by BeardOverflow** [comment]
Dear AlvoErrado,

Youtube-DL cannot download any content from crunchyroll in its latest version according to this issue: https://github.com/rg3/youtube-dl/issues/20027

For some reason, always returns 503 error code.

Some participants are suggesting to spoof the user-agent, but don't looks like be the final solution. I did several test using youtube-dl and I was not able to download anything.

This being the case, I only can wait until the issue in youtube-dl gets resolved. Meanwhile, I will keep open this issue.

**Comment by BeardOverflow** [comment]
Dear AlvoErrado,

I did some changes to support --user-agent argument now. This argument (and --cookies) are required together even for downloading free episodies.

Thanks for reporting and collaborating.

**Comment by arbarbosa1979** [comment]
Thank you very much for your attention, have a nice day.
