### ISSUE TITLE
Merge only with 1 subtittle

### ISSUE THREAD

**Issue by MetalDevOps** [BeardOverflow/MergeCrunch#8]
it is possible to merge only with 1 sub? I would like the final file to be only with the chosen language in the -s argument

Nice script btw, help me a lot.

./mergecrunch.sh -i https://www.crunchyroll.com/pt-br/kaguya-sama-love-is-war/episode-10-kaguya-wont-forgive-kaguya-wants-to-forgive-miyuki-shirogane-wants-to-go-somewhere-782600 -f best -s ptBR -o 'KAGUYA-SAMA: LOVE IS WAR Episódio 10' -c cookies.txt --ua 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36' -g ptBR

**Comment by BeardOverflow** [comment]
Dear whoamikyo,
thanks for your advice. 
Check out the new argument in the latest commit, **--one**
For using, you must specify the target subtitle track. An example: **--one -s ptBR**
